### ISSUE TITLE
PreCompiled Version Possible? Perhaps English Translation?

### ISSUE THREAD

**Issue by DrPariah** [Shazoo/Cataclysm_Util#2]
Looks good so far, but wondering if a precompiled version could be put to Releases? Also, possible to get an English translation?

**Comment by Shazoo** [comment]
Lost the develop environment yet ... 

AFK for months . No plan to modify any code of this repo before next stable version release (0.G.x) .

Next version of this tool will be command line based ( QT waste a lot time to coding UI logic ) , English support will be OK then .

**Comment by DrPariah** [comment]
That's entirely reasonable, and thank you for the update.
